# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-21 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_auto_20170411_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
