# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='goal',
            new_name='values',
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
