# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_auto_20170501_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='title',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
